import type { LandmarkKind } from "@/game/types";

export const WORLD_WIDTH = 2_400;
export const WORLD_HEIGHT = 1_760;

export interface Landmark {
  id: string;
  name: string;
  kind: LandmarkKind;
  x: number;
  y: number;
  entryX: number;
  entryY: number;
  style: "home" | "apartment" | "shop" | "restaurant" | "bank" | "police" | "office" | "fuel" | "depot";
  description: string;
  jobId?: "delivery" | "shop" | "taxi";
}

export const LANDMARKS: Landmark[] = [
  {
    id: "amara-court",
    name: "Amara Court",
    kind: "house",
    x: 360,
    y: 228,
    entryX: 360,
    entryY: 312,
    style: "apartment",
    description: "Your starter flat on a quiet lane.",
  },
  {
    id: "oruama-homes",
    name: "Oruama Homes",
    kind: "house",
    x: 590,
    y: 228,
    entryX: 590,
    entryY: 312,
    style: "home",
    description: "Painted homes with a shared veranda.",
  },
  {
    id: "oruama-grocers",
    name: "Oruama Grocers",
    kind: "shop",
    x: 1_010,
    y: 228,
    entryX: 1_010,
    entryY: 312,
    style: "shop",
    description: "A friendly corner shop for everyday things.",
  },
  {
    id: "mama-nris-kitchen",
    name: "Mama Nri's Kitchen",
    kind: "restaurant",
    x: 1_330,
    y: 228,
    entryX: 1_330,
    entryY: 312,
    style: "restaurant",
    description: "Hot pots, fresh pepper and a place to sit.",
  },
  {
    id: "koru-suites",
    name: "Koru Courtyard House",
    kind: "house",
    x: 1_870,
    y: 228,
    entryX: 1_870,
    entryY: 312,
    style: "home",
    description: "A quiet courtyard home with a shaded front step.",
  },
  {
    id: "koru-fuel",
    name: "Koru Fuel Stop",
    kind: "fuel",
    x: 285,
    y: 735,
    entryX: 285,
    entryY: 819,
    style: "fuel",
    description: "A neighbourhood fuel stop and tyre pump.",
  },
  {
    id: "alao-market",
    name: "Alao Market",
    kind: "shop",
    x: 575,
    y: 735,
    entryX: 575,
    entryY: 819,
    style: "shop",
    description: "Fruit baskets, cloth, cool drinks and busy stalls.",
    jobId: "shop",
  },
  {
    id: "ogbonna-bank",
    name: "Ogbonna Community Bank",
    kind: "bank",
    x: 1_060,
    y: 735,
    entryX: 1_060,
    entryY: 819,
    style: "bank",
    description: "Your in-game Naira balance lives here.",
  },
  {
    id: "sisi-adas-kitchen",
    name: "Sisi Ada's Kitchen",
    kind: "restaurant",
    x: 1_375,
    y: 735,
    entryX: 1_375,
    entryY: 819,
    style: "restaurant",
    description: "A fragrant neighbourhood chop bar.",
  },
  {
    id: "axlori-police-post",
    name: "Axlori Police Post",
    kind: "police",
    x: 1_860,
    y: 735,
    entryX: 1_860,
    entryY: 819,
    style: "police",
    description: "A small community safety post.",
  },
  {
    id: "nembe-towers",
    name: "Nembe Towers",
    kind: "office",
    x: 2_190,
    y: 735,
    entryX: 2_190,
    entryY: 819,
    style: "office",
    description: "Local studios, offices and a rooftop radio room.",
  },
  {
    id: "taxi-rank",
    name: "Riverside Taxi Rank",
    kind: "job",
    x: 665,
    y: 1_435,
    entryX: 665,
    entryY: 1_485,
    style: "depot",
    description: "Pick up a fare for a cross-district run.",
    jobId: "taxi",
  },
  {
    id: "courier-depot",
    name: "Axlori Couriers",
    kind: "job",
    x: 1_030,
    y: 1_405,
    entryX: 1_030,
    entryY: 1_489,
    style: "depot",
    description: "Collect a parcel and deliver it across the district.",
    jobId: "delivery",
  },
  {
    id: "uju-corner-shop",
    name: "Uju's Corner Shop",
    kind: "shop",
    x: 1_365,
    y: 1_405,
    entryX: 1_365,
    entryY: 1_489,
    style: "shop",
    description: "A family-run kiosk with a famous zobo cooler.",
  },
  {
    id: "koru-workshops",
    name: "Koru Motor Works",
    kind: "office",
    x: 1_890,
    y: 1_405,
    entryX: 1_890,
    entryY: 1_489,
    style: "office",
    description: "A fictional local garage and maker shed.",
  },
];
